# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\rong.inventory\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x01\n\x0c\x44onationItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12)\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x17.ong.inventory.Category\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\x12\x0f\n\x07\x64\x65leted\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\ncreated_by\x18\x07 \x01(\t\x12\x12\n\nupdated_at\x18\x08 \x01(\t\x12\x12\n\nupdated_by\x18\t \x01(\t\"\x81\x01\n\x15\x43reateDonationRequest\x12\x16\n\x0e\x61\x63tor_username\x18\x01 \x01(\t\x12)\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x17.ong.inventory.Category\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"b\n\x15UpdateDonationRequest\x12\x16\n\x0e\x61\x63tor_username\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x05\"7\n\x11\x44onationIdRequest\x12\x16\n\x0e\x61\x63tor_username\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\":\n\x0c\x44onationList\x12*\n\x05items\x18\x01 \x03(\x0b\x32\x1b.ong.inventory.DonationItem*G\n\x08\x43\x61tegory\x12\x08\n\x04ROPA\x10\x00\x12\r\n\tALIMENTOS\x10\x01\x12\x0c\n\x08JUGUETES\x10\x02\x12\x14\n\x10UTILES_ESCOLARES\x10\x03\x32\xd4\x02\n\x11\x44onacionesService\x12S\n\x0e\x43reateDonation\x12$.ong.inventory.CreateDonationRequest\x1a\x1b.ong.inventory.DonationItem\x12S\n\x0eUpdateDonation\x12$.ong.inventory.UpdateDonationRequest\x1a\x1b.ong.inventory.DonationItem\x12O\n\x0e\x44\x65leteDonation\x12 .ong.inventory.DonationIdRequest\x1a\x1b.ong.inventory.DonationItem\x12\x44\n\rListDonations\x12\x16.google.protobuf.Empty\x1a\x1b.ong.inventory.DonationListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORY']._serialized_start=620
  _globals['_CATEGORY']._serialized_end=691
  _globals['_DONATIONITEM']._serialized_start=64
  _globals['_DONATIONITEM']._serialized_end=269
  _globals['_CREATEDONATIONREQUEST']._serialized_start=272
  _globals['_CREATEDONATIONREQUEST']._serialized_end=401
  _globals['_UPDATEDONATIONREQUEST']._serialized_start=403
  _globals['_UPDATEDONATIONREQUEST']._serialized_end=501
  _globals['_DONATIONIDREQUEST']._serialized_start=503
  _globals['_DONATIONIDREQUEST']._serialized_end=558
  _globals['_DONATIONLIST']._serialized_start=560
  _globals['_DONATIONLIST']._serialized_end=618
  _globals['_DONACIONESSERVICE']._serialized_start=694
  _globals['_DONACIONESSERVICE']._serialized_end=1034
# @@protoc_insertion_point(module_scope)
