# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import inventory_pb2 as inventory__pb2


class DonacionesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDonation = channel.unary_unary(
                '/ong.inventory.DonacionesService/CreateDonation',
                request_serializer=inventory__pb2.CreateDonationRequest.SerializeToString,
                response_deserializer=inventory__pb2.DonationItem.FromString,
                )
        self.UpdateDonation = channel.unary_unary(
                '/ong.inventory.DonacionesService/UpdateDonation',
                request_serializer=inventory__pb2.UpdateDonationRequest.SerializeToString,
                response_deserializer=inventory__pb2.DonationItem.FromString,
                )
        self.DeleteDonation = channel.unary_unary(
                '/ong.inventory.DonacionesService/DeleteDonation',
                request_serializer=inventory__pb2.DonationIdRequest.SerializeToString,
                response_deserializer=inventory__pb2.DonationItem.FromString,
                )
        self.ListDonations = channel.unary_unary(
                '/ong.inventory.DonacionesService/ListDonations',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=inventory__pb2.DonationList.FromString,
                )


class DonacionesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDonation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDonation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDonation(self, request, context):
        """baja lógica
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDonations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DonacionesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDonation,
                    request_deserializer=inventory__pb2.CreateDonationRequest.FromString,
                    response_serializer=inventory__pb2.DonationItem.SerializeToString,
            ),
            'UpdateDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDonation,
                    request_deserializer=inventory__pb2.UpdateDonationRequest.FromString,
                    response_serializer=inventory__pb2.DonationItem.SerializeToString,
            ),
            'DeleteDonation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDonation,
                    request_deserializer=inventory__pb2.DonationIdRequest.FromString,
                    response_serializer=inventory__pb2.DonationItem.SerializeToString,
            ),
            'ListDonations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDonations,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=inventory__pb2.DonationList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ong.inventory.DonacionesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DonacionesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ong.inventory.DonacionesService/CreateDonation',
            inventory__pb2.CreateDonationRequest.SerializeToString,
            inventory__pb2.DonationItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ong.inventory.DonacionesService/UpdateDonation',
            inventory__pb2.UpdateDonationRequest.SerializeToString,
            inventory__pb2.DonationItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteDonation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ong.inventory.DonacionesService/DeleteDonation',
            inventory__pb2.DonationIdRequest.SerializeToString,
            inventory__pb2.DonationItem.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDonations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ong.inventory.DonacionesService/ListDonations',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            inventory__pb2.DonationList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
